# Generated by Django 4.2.1 on 2023-05-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='colege',
            new_name='college',
        ),
    ]
